const CitiesEnglish = [
    {
        region:"1",
        provinces:"East Azerbaijan",
        Cities:[
            "Ahar",
            "Azarshahr",
            "Bostanabad",
            "Boning-Abad",
            "Bostanabad",
            "Tabriz",
            "Jolfa",
            "Khoja-Afaran",
            "Sarab",
            "Shabestar",
            "AjbiShir",
            "Maragheh",
            "Marand",
            "Malekan",
            "Miyaneh",
            "Heris",
            "Hashtrud",
            "Varzeghan",
            "Charuymaq",
            "Kaleybar"
        ]
    },
    {
        region:"1",
        provinces:
            "West Azerbaijan",
        Cities:[
            "Urmia",
            "Ashna",
            "Baroogh",
            "Bukan",
            "Takab",
            "Khoy",
            "Sardasht",
            "Salamas",
            "Shahin-Dej",
            "Shooshtar",
            "Maku",
            "Mahabad",
            "Miandoab",
            "Naqadeh",
            "Poldasht",
            "Piranshahr",
            "Chaldoran",
            "Chaypareh",
            "Chaharborj"
        ]},
    {
        region:"1",
        provinces:
            "Ardabil",
        Cities:[
            "Ardabil",
            "AslanDuz",
            "Angut",
            "BilehSavar",
            "Khalkhal",
            "Sarein",
            "MeshkinShahr",
            "Namin",
            "Nir",
            "Parsabad",
            "Kosar",
            "Germi"
        ]},{region:"1",
        provinces:
        "Isfahan", Cities:[
            "Aran va Bidgol",
            "Ardestan",
            "Isfahan",
            "Borkhar",
            "Boo & Miandasht",
            "Tiran & Karvan",
            "Jargeh",
            "Khomeinishahr",
            "Khansar",
            "Khour & Biabanak",
            "Dehaqan",
            "Semirom",
            "ShahinShahr & Meymeh",
            "Shahreza",
            "Fereydun",
            "FereydunShahr",
            "Falavarjan",
            "Lenjan",
            "Mobarakeh",
            "Nain",
            "Najafabad",
            "Natanz",
            "Harend",
            "Varzaneh",
            "Chadegan",
            "Kashan",
            "Kuhpayeh",
            "Golpayegan"
        ]},{region:"2", provinces:
        "Alborz", Cities:[
            "Eslamshahr",
            "Savojbolagh",
            "Taleqan",
            "Fardis",
            "Nazarabad",
            "Chaharbagh",
            "Karaj"
        ]},{region:"2", provinces:
        "Ilam", Cities:[
            "Abdanan",
            "Ilam",
            "Ivan",
            "Badreh",
            "Darreh Shahr",
            "Dehloran",
            "Sirvan",
            "Malekshahi",
            "Mehran",
            "Hililan",
            "Chardavol",
            "Chavar"
        ]},{region:"2", provinces:
        "Bushehr", Cities:[
            "Bushehr",
            "Tangestan",
            "Jame",
            "Dashtestan",
            "Dashti",
            "Deylam",
            "Dir",
            "Delm",
            "Assaluyeh",
            "Kangan",
            "Ganaveh"
        ]},{region:"1", provinces:
        "Tehran", Cities:[
            "Islamshahr",
            "Baharestan",
            "Tehran",
            "Damavand",
            "Robat Karim",
            "Ray",
            "Shemiranat",
            "Shahriar",
            "Firuzkuh",
            "Ghods",
            "Qarchak",
            "Malard",
            "Varamin",
            "Pakdasht",
            "Pardis",
            "Pishva"
        ]},{region:"2", provinces:
        "South Khorasan", Cities:[
            "Birjand",
            "Boshruyeh",
            "Khosef",
            "Darmian",
            "Zirkuh",
            "Sarayan",
            "Sarbisheh",
            "Tabas",
            "Ferdows",
            "Qaen",
            "Nehbandan"
        ]},{region:"1", provinces:
        "Razavi Khorasan", Cities:[
            "Bakharz",
            "Bojnoord",
            "Bardaskan",
            "Binolord",
            "Taybad",
            "Torbat Jam",
            "Torbat Heydariyeh",
            "Joghatai",
            "Jovein",
            "Khalilabad",
            "Khaf",
            "Khoshab",
            "Davarzan",
            "Dargaz",
            "Rashtkhar",
            "Zaveh",
            "Sabzevar",
            "Sarakhs",
            "Sheshtamad",
            "Firiman",
            "Firuzeh",
            "Ghouchan",
            "Mashhad",
            "Mehvalat",
            "Neyshabur",
            "Chenaran",
            "Kashmar",
            "Kalat",
            "Koohsar",
            "Golbahar",
            "Gonabad"
        ]},{region:"2", provinces:
        "North Khorasan", Cities:[
            "Esfarayen",
            "Bojnord",
            "Jajarm",
            "Raz and Jargalan",
            "Shirvan",
            "Faruj",
            "Maneh and Samalqan",
            "Garmeh"
        ]},{region:"1", provinces:
        "Khuzestan", Cities:[
            "Abadan",
            "Aghajari",
            "Omidieh",
            "Andimeshk",
            "Andika",
            "Ahvaz",
            "Izeh",
            "Baghmalek",
            "Bavi",
            "Bandar Mahshahr",
            "Behbahan",
            "Khorramshahr",
            "Dezful",
            "Dezpart",
            "Dasht-e Azadegan",
            "Ramshir",
            "Ramhormoz",
            "Shadegan",
            "Shushtar",
            "Shush",
            "Lali",
            "Masjed Soleyman",
            "Haftkel",
            "Hendijan",
            "Hoveyzeh",
            "Karun",
            "Karkheh",
            "Gotvand"
        ]},{region:"2", provinces:
        "Zanjan", Cities:[
            "Abhar",
            "Ijroud",
            "Khodabandeh",
            "Khorramdarreh",
            "Zanjan",
            "Soltaniyeh",
            "Tarom",
            "Mah Neshan"
        ]},{region:"1", provinces:
        "Semnan", Cities:[
            "Aradan",
            "Damghan",
            "Sorkheh",
            "Semnan",
            "Shahrood",
            "Mehdishahr",
            "MiyanDoab",
            "Garmsar"
        ]},{region:"2", provinces:
        "Sistan and Baluchestan", Cities:[
            "Iran Shahr",
            "Taftan",
            "Khash",
            "Dashtiari",
            "Delgan",
            "Rask",
            "Zabol",
            "Zahedan",
            "Zarabad",
            "Zahak",
            "Saravan",
            "Sarbaz",
            "Sib and Suran",
            "Fenouj",
            "GhasreGhand",
            "Lashar",
            "Mehrestan",
            "Mirjaveh",
            "Nimruz",
            "Nikshahr",
            "Hamun",
            "Hirmand",
            "Chabahar",
            "Konarak",
            "Golshan"
        ]},{region:"1", provinces:
        "Fars", Cities:[
            "Abadeh",
            "Esfahan",
            "Estahban",
            "Eqleed",
            "Owsat",
            "Bakhtegan",
            "Boanat",
            "Beyza",
            "Jahrom",
            "Kharameh",
            "Khonj",
            "Darab",
            "Rostam",
            "Zarqan",
            "ZarinDasht",
            "Sarvestan",
            "Sar ChahAn",
            "Sepidan",
            "Shiraz",
            "Firuzabad",
            "Fasa",
            "FiruzAbad",
            "GhirKarzin",
            "Lar",
            "Lamerd",
            "Marvdasht",
            "Mamasani",
            "Mehr",
            "Neyriz",
            "Pasargad",
            "Kazerun",
            "Kovar",
            "Kuhchenar",
            "Garach"
        ]},{region:"2", provinces:
        "Qazvin", Cities:[
            "AbiK",
            "Avaj",
            "Alborz",
            "BuinZahra",
            "Takestan",
            "Qazvin"
        ]},{region:"1", provinces:
        "Qom", Cities:[
            "Jafarabad",
            "Qom",
            "Kahak"
        ]},{region:"1", provinces:
        "Lorestan", Cities:[
            "Azna",
            "Aligudarz",
            "Borujerd",
            "Khorramabad",
            "Delfan",
            "Dorud",
            "Dorud",
            "Rumeshkhan",
            "Pol-e Dokhtar",
            "Kuhdasht"
        ]},{region:"2", provinces:
        "Mazandaran", Cities:[
            "Amol",
            "Babol",
            "Babolsar",
            "Behshahr",
            "Tonekabon",
            "Juybar",
            "Ramsar",
            "Sari",
            "Northern Savadkooh",
            "Savadkooh",
            "Simorgh",
            "Abbasabad",
            "Fereydunkenar",
            "Ghaemshahr",
            "Mahmoudabad",
            "Miandorud",
            "Nur",
            "Noshahr",
            "Neka",
            "Chalus",
            "Kalardasht",
            "Galugah"
        ]},{region:"2", provinces:
        "Markazi", Cities:[
            "Ashtian",
            "Arak",
            "Tafresh",
            "Khomein",
            "Khandab",
            "Delijan",
            "Zarandieh",
            "Saveh",
            "Shazand",
            "Firuzan",
            "Mahallat",
            "Komijan"
        ]},{region:"1", provinces:
        "Hormozgan", Cities:[
            "Abu Musa",
            "Bushehr",
            "Boshagar",
            "Bandar Lengeh",
            "Bandar Abbas",
            "Jask",
            "Hajiabad",
            "Khormoj",
            "Roodan",
            "Sirik",
            "Qeshm",
            "Minab",
            "Parsian"
        ]},{region:"1", provinces:
        "Hamadan", Cities:[
            "Asadabad",
            "Bahar",
            "Tuyserkan",
            "Razan",
            "Famenin",
            "Malayer",
            "Nahavand",
            "Hamadan",
            "Kabudar Ahang"
        ]},{region:"1", provinces:
        "Chaharmahal and Bakhtiari", Cities:[
            "Ardal",
            "Boroujen",
            "Ben",
            "Samana",
            "Shahr-e Kord",
            "Farsan",
            "Lordegan",
            "Kuhrang",
            "Kiar"
        ]},{region:"3", provinces:
        "Kurdistan", Cities:[
            "Baneh",
            "Bijar",
            "Dehgolan",
            "Divandareh",
            "Sarvabad",
            "Saqqez",
            "Sanandaj",
            "Qorveh",
            "Marivan",
            "Kamyaran"
        ]},{region:"4", provinces:
        "Kerman", Cities:[
            "Arzuiyeh",
            "Anar",
            "Baft",
            "Bardsir",
            "Bam",
            "Jiroft",
            "Rabor",
            "Ravar",
            "Rafsanjan",
            "Roodbar-e Jonubi",
            "Rigan",
            "Zarand",
            "Sirjan",
            "Shahr-e Babak",
            "Anbarabad",
            "Faryab",
            "Fahraj",
            "Ghaleh Ganj",
            "Manujan",
            "Narmashir",
            "Kerman",
            "Kahnooj",
            "Koohbanan"
        ]},{region:"5", provinces:
        "Kermanshah", Cities:[
            "Eslamabad-e Gharb",
            "Salas-e Babajani",
            "Javanrud",
            "Dalahu",
            "Ravansar",
            "Sarpol-e Zahab",
            "Sanandaj",
            "Sahneh",
            "Qasr-e Shirin",
            "Harsin",
            "Paveh",
            "Kermanshah",
            "Kangavar",
            "Gilan-e Gharb"
        ]},{region:"4", provinces:
        "Kohgiluyeh and Boyer-Ahmad", Cities:[
            "Basht",
            "Bahmai",
            "Boyer-Ahmad",
            "Dana",
            "Landeh",
            "Margoon",
            "Charam",
            "Kohgiluyeh",
            "Gachsaran"
        ]},{region:"2", provinces:
        "Golestan", Cities:[
            "Azadshahr",
            "Aqqala",
            "Bandar Gaz",
            "Torkaman",
            "Ramian",
            "Aliabad",
            "Maraveh Tappeh",
            "Minudasht",
            "Gorgan",
            "Gomishan",
            "Galikash",
            "Gonbad-e Kavus"
        ]},{region:"5", provinces:
        "Gilan", Cities:[
            "Astara",
            "Astaneh-ye Ashrafiyeh",
            "Amlash",
            "Bandar Anzali",
            "Talesh",
            "Rudsar",
            "Rasht",
            "Rezvanshahr",
            "Lahijan",
            "Langeroud",
            "Shaft",
            "Siahkal",
            "Masal",
            "Fooman",
            "Rudbar",
            "Rostamabad"
        ]},{region:"5", provinces:
        "Fars", Cities:[
            "Abadeh",
            "Esfahan",
            "Estahban",
            "Eqleed",
            "Owsat",
            "Bakhtegan",
            "Boanat",
            "Beyza",
            "Jahrom",
            "Kharameh",
            "Khonj",
            "Darab",
            "Rostam",
            "Zarqan",
            "ZarinDasht",
            "Sarvestan",
            "Sar ChahAn",
            "Sepidan",
            "Shiraz",
            "Firuzabad",
            "Fasa",
            "FiruzAbad",
            "GhirKarzin",
            "Lar",
            "Lamerd",
            "Marvdasht",
            "Mamasani",
            "Mehr",
            "Neyriz",
            "Pasargad",
            "Kazerun",
            "Kovar",
            "Kuhchenar",
            "Garach"
        ]},{region:"4", provinces:
        "Khorasan Razavi", Cities:[
            "Bakharz",
            "Bojnoord",
            "Bardaskan",
            "Binolord",
            "Taybad",
            "Torbat Jam",
            "Torbat Heydariyeh",
            "Joghatai",
            "Jovein",
            "Khalilabad",
            "Khaf",
            "Khoshab",
            "Davarzan",
            "Dargaz",
            "Rashtkhar",
            "Zaveh",
            "Sabzevar",
            "Sarakhs",
            "Sheshtamad",
            "Firiman",
            "Firuzeh",
            "Ghouchan",
            "Mashhad",
            "Mehvalat",
            "Neyshabur",
            "Chenaran",
            "Kashmar",
            "Kalat",
            "Koohsar",
            "Golbahar",
            "Gonabad"
        ]},{region:"4", provinces:
        "Kurdistan", Cities:[
            "Baneh",
            "Bijar",
            "Dehgolan",
            "Divandareh",
            "Sarvabad",
            "Saqqez",
            "Sanandaj",
            "Qorveh",
            "Marivan",
            "Kamyaran"
        ]},{region:"3", provinces:
        "Kerman", Cities:[
            "Arzuiyeh",
            "Anar",
            "Baft",
            "Bardsir",
            "Bam",
            "Jiroft",
            "Rabor",
            "Ravar",
            "Rafsanjan",
            "Roodbar-e Jonubi",
            "Rigan",
            "Zarand",
            "Sirjan",
            "Shahr-e Babak",
            "Anbarabad",
            "Faryab",
            "Fahraj",
            "Ghaleh Ganj",
            "Manujan",
            "Narmashir",
            "Kerman",
            "Kahnooj",
            "Koohbanan"
        ]},{region:"2", provinces:
        "Kermanshah", Cities:[
            "Eslamabad-e Gharb",
            "Salas-e Babajani",
            "Javanrud",
            "Dalahu",
            "Ravansar",
            "Sarpol-e Zahab",
            "Sanandaj",
            "Sahneh",
            "Qasr-e Shirin",
            "Harsin",
            "Paveh",
            "Kermanshah",
            "Kangavar",
            "Gilan-e Gharb"
        ]},{region:"4", provinces:
        "Kohgiluyeh and Boyer-Ahmad", Cities:[
            "Basht",
            "Bahmai",
            "Boyer-Ahmad",
            "Dana",
            "Landeh",
            "Margoon",
            "Charam",
            "Kohgiluyeh",
            "Gachsaran"
        ]},{region:"3", provinces:
        "Golestan", Cities:[
            "Azadshahr",
            "Aqqala",
            "Bandar Gaz",
            "Torkaman",
            "Ramian",
            "Aliabad",
            "Maraveh Tappeh",
            "Minudasht",
            "Gorgan",
            "Gomishan",
            "Galikash",
            "Gonbad-e Kavus"
        ]},{region:"3", provinces:
        "Gilan", Cities:[
            "Astara",
            "Astaneh-ye Ashrafiyeh",
            "Amlash",
            "Bandar Anzali",
            "Talesh",
            "Rudsar",
            "Rasht",
            "Rezvanshahr",
            "Lahijan",
            "Langeroud",
            "Shaft",
            "Siahkal",
            "Masal",
            "Fooman",
            "Rudbar",
            "Rostamabad"
        ]},{region:"3", provinces:
        "Gorgan", Cities:[
            "Aliabad",
            "Gorgan",
            "Gonbad-e Kavus",
            "Kalaleh",
            "Kordkuy",
            "Minudasht",
            "Bandar Torkaman",
            "Torkaman"
        ]},{region:"2", provinces:
        "Fars", Cities:[
            "Abadeh",
            "Esfahan",
            "Estahban",
            "Eqleed",
            "Owsat",
            "Bakhtegan",
            "Boanat",
            "Beyza",
            "Jahrom",
            "Kharameh",
            "Khonj",
            "Darab",
            "Rostam",
            "Zarqan",
            "ZarinDasht",
            "Sarvestan",
            "Sar ChahAn",
            "Sepidan",
            "Shiraz",
            "Firuzabad",
            "Fasa",
            "FiruzAbad",
            "GhirKarzin",
            "Lar",
            "Lamerd",
            "Marvdasht",
            "Mamasani",
            "Mehr",
            "Neyriz",
            "Pasargad",
            "Kazerun",
            "Kovar",
            "Kuhchenar",
            "Garach"
        ]},{region:"5", provinces:
        "Khorasan Razavi", Cities:[
            "Bakharz",
            "Bojnoord",
            "Bardaskan",
            "Binolord",
            "Taybad",
            "Torbat Jam",
            "Torbat Heydariyeh",
            "Joghatai",
            "Jovein",
            "Khalilabad",
            "Khaf",
            "Khoshab",
            "Davarzan",
            "Dargaz",
            "Rashtkhar",
            "Zaveh",
            "Sabzevar",
            "Sarakhs",
            "Sheshtamad",
            "Firiman",
            "Firuzeh",
            "Ghouchan",
            "Mashhad",
            "Mehvalat",
            "Neyshabur",
            "Chenaran",
            "Kashmar",
            "Kalat",
            "Koohsar",
            "Golbahar",
            "Gonabad"
        ]},{region:"2", provinces:
        "Kurdistan", Cities:[
            "Baneh",
            "Bijar",
            "Dehgolan",
            "Divandareh",
            "Sarvabad",
            "Saqqez",
            "Sanandaj",
            "Qorveh",
            "Marivan",
            "Kamyaran"
        ]},{region:"3", provinces:
        "Kerman", Cities:[
            "Arzuiyeh",
            "Anar",
            "Baft",
            "Bardsir",
            "Bam",
            "Jiroft",
            "Rabor",
            "Ravar",
            "Rafsanjan",
            "Roodbar-e Jonubi",
            "Rigan",
            "Zarand",
            "Sirjan",
            "Shahr-e Babak",
            "Anbarabad",
            "Faryab",
            "Fahraj",
            "Ghaleh Ganj",
            "Manujan",
            "Narmashir",
            "Kerman",
            "Kahnooj",
            "Koohbanan"
        ]},{region:"4", provinces:
        "Kermanshah", Cities:[
            "Eslamabad-e Gharb",
            "Salas-e Babajani",
            "Javanrud",
            "Dalahu",
            "Ravansar",
            "Sarpol-e Zahab",
            "Sanandaj",
            "Sahneh",
            "Qasr-e Shirin",
            "Harsin",
            "Paveh",
            "Kermanshah",
            "Kangavar",
            "Gilan-e Gharb"
        ]},{region:"4", provinces:
        "Kohgiluyeh and Boyer-Ahmad", Cities:[
            "Basht",
            "Bahmai",
            "Boyer-Ahmad",
            "Dana",
            "Landeh",
            "Margoon",
            "Charam",
            "Kohgiluyeh",
            "Gachsaran"
        ]},{region:"3", provinces:
        "Golestan", Cities:[
            "Azadshahr",
            "Aqqala",
            "Bandar Gaz",
            "Torkaman",
            "Ramian",
            "Aliabad",
            "Maraveh Tappeh",
            "Minudasht",
            "Gorgan",
            "Gomishan",
            "Galikash",
            "Gonbad-e Kavus"
        ]},{region:"1", provinces:
        "Gilan", Cities:[
            "Astara",
            "Astaneh-ye Ashrafiyeh",
            "Amlash",
            "Bandar Anzali",
            "Talesh",
            "Rudsar",
            "Rasht",
            "Rezvanshahr",
            "Lahijan",
            "Langeroud",
            "Shaft",
            "Siahkal",
            "Masal",
            "Fooman",
            "Rudbar",
            "Rostamabad"
        ]},
    {region:"2", provinces:
        "Gorgan", Cities:[
            "Aliabad",
            "Gorgan",
            "Gonbad-e Kavus",
            "Kalaleh",
            "Kordkuy",
            "Minudasht",
            "Bandar Torkaman",
            "Torkaman"
        ]
    }
]

export default CitiesEnglish;